kind: Deployment
apiVersion: apps/v1

metadata:
  name: goserver
  labels:
    app: goserver

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: ericoalmeida/hello-go:1.2
          envFrom:
            - configMapRef:
                name: goserver-envs
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000

# Deployment creates ReplicaSet that creates pods.
# In this case, the deployment load all configMap environments.